spring:
  application:
    name: SprinBoot_Mapping

  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true